### PR TITLE
Add support for Angular 18, Angular Material 18 and Material 3 design

### LINKED ISSUE #132: M3 support?
Does it support Material V3? Or are there any plans to support it in the future?

### PR DESCRIPTION
**Pull request by shhdharmen**
@dhutaryan Thanks for creating this awesome library. I am creating this PR to add support for below:

1. Angular 18
2. Angular Material 18
3. Material 3 Design (keeping support for Material 2)

This should close #132 #152

### CODE REVIEW

**Comment by shhdharmen** [comment]
Attaching screenshots for easy review.

Screenshot 2024-06-27 at 11 34 45 AM
Screenshot 2024-06-27 at 11 34 58 AM
Screenshot 2024-06-27 at 11 35 31 AM
Screenshot 2024-06-27 at 11 35 40 AM

**Comment by howdysuraj** [comment]
Nice

**Comment by anabright** [comment]
Thanks @shhdharmen!
@dhutaryan any plans to merge & release this?

**Comment by dhutaryan** [comment]
@shhdharmen hey, thank you for that awesome work. I've started to work on it some time ago and wanted to add one more feature. I'm 100% sure we will have merge conflicts. So, if you don't mind I'll take a big part of your changes to my branch.
By the way, why did you change the size of fat buttons?

@anabright soon, didn't have time to handle it

**Comment by shhdharmen** [comment]
@dhutaryan yes, feel free to take my changes in your branch. Which buttons are you referring to? I tried to follow specs from https://m3.material.io/components/time-pickers/specs

**Comment by anabright** [comment]
No worries, thanks for your reply @dhutaryan, I just thought I'd give you a nudge ;)

**Pull request closed without merging**
